### ISSUE TITLE
感谢你对platformview的贡献

### ISSUE THREAD

**Issue by chenenyu** [0xZOne/platform_view_test#1]
之前在使用PlatformView的时候，在Android平台(特别是华为/荣耀的机型)，出现了比较多的兼容性问题，新的texture的方式不知道在国产机上的兼容性问题怎么样。

**Comment by 0xZOne** [comment]
官方 https://github.com/flutter/engine/pull/33599 上线后，加上之前我们修复的两个问题（ https://github.com/flutter/engine/pull/33655 ， https://github.com/flutter/engine/pull/31698 ），新方案现在应该问题不大了。关注一下 https://github.com/flutter/flutter/issues/107313 的进展。

**Comment by 0xZOne** [comment]
可以关注一下：https://github.com/flutter/flutter/issues/107313 的进展

**Comment by chenenyu** [comment]
关注了https://github.com/flutter/flutter/issues/107313 ，就像issue里描述的一样，现在3种模式混合在一起对现有的插件影响较大，我这边大量使用了platformview，希望尽快稳定吧

**Comment by 0xZOne** [comment]
嗯，现在platform view相关的问题应该都有解决方案了，只是模式选择比较混乱，处理起来有些麻烦。

**Comment by zmGitHub** [comment]
还是复现了各种问题 导致地图相关的plugin都不能用了

**Comment by 0xZOne** [comment]
> 还是复现了各种问题 导致地图相关的plugin都不能用了

当前是 Virtual Display、Hybrid Composition以及最新的TLHC三种方案共存，所以问题应该都是可以解决的。只是默认方案变了，可能需要针对具体场景手动修改一下～
